name: read_to_me
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  drag_and_drop_gridview: ^1.0.8
  loadinglistview: ^0.0.2
#  firebase_auth: ^3.0.1
  loading_more_list: any
  dropdown_search: ^0.6.3
  http: ^0.13.3
  google_sign_in: ^5.0.7
  loading_overlay_pro: ^2.1.1
  progress_indicators: ^1.0.0
  intl: ^0.17.0

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_switch: ^0.3.2
  iphone_has_notch: ^1.0.0
  url_launcher: ^6.0.9
  share: ^2.0.4
  flutter_tts: ^3.2.1
  speech_to_text: ^4.2.2
  toast: ^0.1.5
  flutter_rating_bar: ^4.0.0
  flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - facebook.png
    - hdhdhd.jpg
    - imggfcgf.jpg
    - imgh.jpg
    - search.png
    - mail.png
    - apple.png
    - close.png
    - man-user.png
    - MaskGroup15.png
    - united-states.png
    - star.png
    - krishna.png
    - shsh.jpg
    - aaa.png
    - envelope.png
    - left-arrow.png
    - a.png
    - pause.png
    - avenger.jpg
    - Avengers.jpg
    - add.png
    - magnifying-glass.png
    - awm.jpg
    - amau.jpg
    - subfolder.png
    - headphones.png
    - history.png
    - favourite.png
    - speedometer.png
    - arrow.png
    - Image.jpg
    - favourite.png
    - settings.png
    - king.png
    - star.png
    - girl.png
    - facebook.png
    - instagram.png
    - youtube.png
    - google-symbol.png
    - gmail.png
    - switch.png
    - library.png
    - courses.png
    - historyUnselected.png
    - historySelected.png
    - bubble.png
    - Golden-Duel.png
    - word-craft.jpg
    - games.png
    - degree.png
    - progress-report.png
    - clock.png
    - chat.png
    - man.png
    - show.png
    - Tome.jpg
    - bookmark.png
    - book.png
    - headphones.png
    - study-man.jpg
    - student.png
    - degreeUnselected.png
    - chatUnselected.png
    - gamesUnselected.png
    - coursesUnselected.png
    - settingsUnselected.png
    - upload.png
    - bookmark_1.png
    - bookmark-not.png
    - download.png
    - agenda.png
    - crown.png
    - chatUnselected.png
    - chatSelected.png
    - speeker_Red.png
    - default-Photos.png



  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
